#!/usr/bin/env python

# Purpose: Calculate the lateral pressure profile from a strees tensor data 
#          file generated by gromacs_LS.
# Note: 
# Syntax: stress2lpp.py stress.txt Pn > lpp.txt
# Created: 2016/Mar/15

from __future__ import print_function 
import sys


if len(sys.argv) is not 3:
    print("Syntax: stress2lpp.py stress.txt Pn > lpp.txt")
    sys.exit()


with open(sys.argv[1] , 'rt') as stressFile:
    lines = stressFile.readlines()
Pn = float(sys.argv[2])

header = lines.pop(0)
if header[0] is not '#':
    print("Wrong format! Check 1st line.")
    sys.exit()

titleLine = lines.pop(0)
if header[0] is not '#':
    print("Wrong format! Check 2nd line.")
    sys.exit()
else:
    titles = titleLine.split()
    if titles[2] != 'Sxx' or titles[6] != 'Syy' or titles[10] != 'Szz':
        print("Wrong format! Check 2nd line.")
        sys.exit()

print("# %s lpp" % titles[1]) 
for line in lines:
    words = line.split()
    coord = words[0]
    pxx = -float(words[1])
    pyy = -float(words[5])
    pzz = -float(words[9])
    
    lpp = 0.5 * (pxx + pyy) - Pn
    print(coord, lpp)
